# Experimental Results for Error

In [7]:
import pandas as pd
import os
from utils import *

In [8]:
res_columns = ['Calibrated on', 'Art', 'Clipart', 'Product', 'RealWorld', 'Average']

## Load the Error Dataframe when source domain is included in calibration domains.

### KFold results of best Rho based on both Error and Error

In [9]:
best_rho_er_in = best_rho_calib('Error', 'in', 'crossentropy')
best_rho_ece_in = best_rho_calib('ECE', 'in', 'crossentropy')

In [10]:
best_rho_er_in

{'Art': {'Product_RealWorld': 0.2,
  'Clipart_RealWorld': 0.2,
  'Clipart_Product': 0.2},
 'Clipart': {'Product_RealWorld': 0.3,
  'Art_RealWorld': 0.3,
  'Art_Product': 0.3},
 'Product': {'Clipart_RealWorld': 0.2,
  'Art_RealWorld': 0.2,
  'Art_Clipart': 0.3},
 'RealWorld': {'Clipart_Product': 0.2, 'Art_Product': 0.3, 'Art_Clipart': 0.2}}

In [11]:
error_file_in = os.path.join('..', '..', 'results', 'OfficeHome', 'crossentropy', 'in_Error_mean.csv')
error_in = pd.read_csv(error_file_in)
error_in = get_res_df(error_in, best_rho_er_in, best_rho_ece_in)

### Average the domain wise results for target domains
We also have stored results for std. Here we are abusing the statistics by taking the standard deviation over columns. We ran the 20 iterations over 500 randomly selected samples. By abusing we are treating these columns as single iteration results.

In [12]:
res_mean_in = error_in[MAIN_COLUMNS+['Domain']][(error_in['Valid'] == False) & (error_in['Train'] == False)].groupby(['Domain']).mean().T
res_std_in = error_in[MAIN_COLUMNS+['Domain']][(error_in['Valid'] == False) & (error_in['Train'] == False)].groupby(['Domain']).std().T

In [13]:
res_mean_in['Average'] = res_mean_in[['Art', 'Clipart', 'Product', 'RealWorld']].mean(axis=1)

Get the standard deviations for Average. The function is in utils.py

In [14]:
res_std_in['std'] = get_std(res_mean_in, res_std_in)

In [15]:
res_mean_in = res_mean_in.round(2)
res_std_in = res_std_in.round(2)

In [16]:
res_mean_in['Art'] = res_mean_in['Art'].astype(str) + '+' + res_std_in['Art'].astype(str)
res_mean_in['Clipart'] = res_mean_in['Clipart'].astype(str) + '+' + res_std_in['Clipart'].astype(str)
res_mean_in['Product'] = res_mean_in['Product'].astype(str) + '+' + res_std_in['Product'].astype(str)
res_mean_in['RealWorld'] = res_mean_in['RealWorld'].astype(str) + '+' + res_std_in['RealWorld'].astype(str)
res_mean_in['Average'] = res_mean_in['Average'].astype(str) + '+' + res_std_in['std'].astype(str)

#### Show the results

In [17]:
res_mean_in['Calibrated on'] = ['in'] * len(res_mean_in)
res_mean_in.rename_axis('Method', axis='columns', inplace=True)

In [18]:
res_mean_in[res_columns]

Method,Calibrated on,Art,Clipart,Product,RealWorld,Average
Uncalibrated,in,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
TS Source,in,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
TS Oracle,in,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
HB,in,80.3+3.97,78.36+2.09,69.3+4.43,65.94+5.25,73.48+7.28
Isotonic,in,77.45+3.57,75.18+2.0,63.5+4.27,59.82+5.04,68.99+8.43
Beta abm,in,77.04+4.77,74.65+2.04,62.14+6.38,58.04+5.96,67.97+9.52
Beta am,in,76.61+4.75,74.45+2.16,61.81+6.33,57.71+5.51,67.64+9.45
Beta ab,in,78.41+4.57,75.79+2.48,63.56+6.02,59.14+6.38,69.23+9.55
TS,in,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
Cluster NN,in,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
Cluster LR,in,78.0+4.67,75.69+2.3,63.32+6.38,58.8+6.68,68.95+9.68
Cluster Ensem,in,78.0+4.67,75.69+2.3,63.32+6.38,58.8+6.68,68.95+9.68
CaliGen Er,in,72.71+2.4,71.94+0.17,57.97+1.69,51.34+5.36,63.49+9.64
CaliGen TS Er,in,72.71+2.4,71.94+0.17,57.97+1.69,51.34+5.36,63.49+9.64
CaliGen Ensem Er,in,73.76+3.93,72.45+1.5,58.75+4.07,52.42+6.23,64.35+10.01
CaliGen ECE,in,72.37+1.88,72.22+0.54,57.69+1.26,51.13+5.0,63.35+9.64
CaliGen TS ECE,in,72.37+1.88,72.22+0.54,57.69+1.26,51.13+5.0,63.35+9.64
CaliGen Ensem ECE,in,73.42+3.55,72.45+1.5,58.56+3.91,52.41+5.94,64.21+9.87

## Load the Error Dataframe when source domain is not included in calibration domains.

### KFold results of best Rho based on both Error and Error

In [19]:
best_rho_er_out = best_rho_calib('Error', 'out', 'crossentropy')
best_rho_ece_out = best_rho_calib('ECE', 'out', 'crossentropy')

In [22]:
error_file_out = os.path.join('..', '..', 'results', 'OfficeHome', 'crossentropy', 'out_Error_mean.csv')
error_out = pd.read_csv(error_file_out)
error_out = get_res_df(error_out, best_rho_er_out, best_rho_ece_out)

### Average the domain wise results for target domains when source domain not included in calibration domain
We also have stored results for std. Here we are abusing the statistics by taking the standard deviation over columns. We ran the 20 iterations over 500 randomly selected samples. By abusing we are treating these columns as single iteration results.

In [23]:
res_mean_out = error_out[MAIN_COLUMNS+['Domain']][(error_out['Valid'] == False) & (error_out['Train'] == False)].groupby(['Domain']).mean().T
res_std_out = error_out[MAIN_COLUMNS+['Domain']][(error_out['Valid'] == False) & (error_out['Train'] == False)].groupby(['Domain']).std().T

Get the standard deviations for Average. The function is in utils.py

In [24]:
res_mean_out['Average'] = res_mean_out[['Art', 'Clipart', 'Product', 'RealWorld']].mean(axis=1)
res_std_out['std'] = get_std(res_mean_out, res_std_out)

In [25]:
res_mean_out = res_mean_out.round(2)
res_std_out = res_std_out.round(2)

In [26]:
res_mean_out['Art'] = res_mean_out['Art'].astype(str) + '+' + res_std_out['Art'].astype(str)
res_mean_out['Clipart'] = res_mean_out['Clipart'].astype(str) + '+' + res_std_out['Clipart'].astype(str)
res_mean_out['Product'] = res_mean_out['Product'].astype(str) + '+' + res_std_out['Product'].astype(str)
res_mean_out['RealWorld'] = res_mean_out['RealWorld'].astype(str) + '+' + res_std_out['RealWorld'].astype(str)
res_mean_out['Average'] = res_mean_out['Average'].astype(str) + '+' + res_std_out['std'].astype(str)

#### Show the results

In [27]:
res_mean_out['Calibrated on'] = ['out'] * len(res_mean_out)
res_mean_out.rename_axis('Method', axis='columns', inplace=True)

In [28]:
res_mean_out[res_columns]

Method,Calibrated on,Art,Clipart,Product,RealWorld,Average
Uncalibrated,out,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
TS Source,out,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
TS Oracle,out,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
HB,out,82.0+3.66,80.62+0.92,73.45+1.71,70.67+4.71,76.68+5.69
Isotonic,out,78.72+2.71,76.43+1.54,67.83+2.0,66.01+3.77,72.25+6.03
Beta abm,out,77.07+4.3,74.66+2.06,62.71+5.36,58.71+5.15,68.29+8.92
Beta am,out,76.68+4.35,74.43+2.3,62.69+5.4,58.77+5.17,68.14+8.8
Beta ab,out,78.4+4.57,75.8+2.24,63.76+6.07,59.42+6.35,69.34+9.44
TS,out,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
Cluster NN,out,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
Cluster LR,out,78.0+4.67,75.69+2.3,63.32+6.38,58.8+6.68,68.95+9.68
Cluster Ensem,out,78.0+4.67,75.69+2.3,63.32+6.38,58.8+6.68,68.95+9.68
CaliGen Er,out,74.57+1.41,73.54+1.12,60.31+3.75,54.15+5.21,65.64+9.31
CaliGen TS Er,out,74.57+1.41,73.54+1.12,60.31+3.75,54.15+5.21,65.64+9.31
CaliGen Ensem Er,out,73.36+2.19,72.25+1.44,58.5+2.54,52.59+6.09,64.18+9.57
CaliGen ECE,out,74.15+0.92,73.89+0.76,60.37+3.81,55.23+5.96,65.91+9.05
CaliGen TS ECE,out,74.15+0.92,73.89+0.76,60.37+3.81,55.23+5.96,65.91+9.05
CaliGen Ensem ECE,out,73.95+1.18,72.35+1.39,58.88+1.94,52.5+5.79,64.42+9.58

## Combined results when source domain included (in) and not included (out) in calibration domains

In [29]:
res = pd.concat([res_mean_in[res_columns], res_mean_out[res_columns]])

In [30]:
res

Method,Calibrated on,Art,Clipart,Product,RealWorld,Average
Uncalibrated,in,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
TS Source,in,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
TS Oracle,in,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
HB,in,80.3+3.97,78.36+2.09,69.3+4.43,65.94+5.25,73.48+7.28
Isotonic,in,77.45+3.57,75.18+2.0,63.5+4.27,59.82+5.04,68.99+8.43
Beta abm,in,77.04+4.77,74.65+2.04,62.14+6.38,58.04+5.96,67.97+9.52
Beta am,in,76.61+4.75,74.45+2.16,61.81+6.33,57.71+5.51,67.64+9.45
Beta ab,in,78.41+4.57,75.79+2.48,63.56+6.02,59.14+6.38,69.23+9.55
TS,in,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
Cluster NN,in,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
Cluster LR,in,78.0+4.67,75.69+2.3,63.32+6.38,58.8+6.68,68.95+9.68
Cluster Ensem,in,78.0+4.67,75.69+2.3,63.32+6.38,58.8+6.68,68.95+9.68
CaliGen Er,in,72.71+2.4,71.94+0.17,57.97+1.69,51.34+5.36,63.49+9.64
CaliGen TS Er,in,72.71+2.4,71.94+0.17,57.97+1.69,51.34+5.36,63.49+9.64
CaliGen Ensem Er,in,73.76+3.93,72.45+1.5,58.75+4.07,52.42+6.23,64.35+10.01
CaliGen ECE,in,72.37+1.88,72.22+0.54,57.69+1.26,51.13+5.0,63.35+9.64
CaliGen TS ECE,in,72.37+1.88,72.22+0.54,57.69+1.26,51.13+5.0,63.35+9.64
CaliGen Ensem ECE,in,73.42+3.55,72.45+1.5,58.56+3.91,52.41+5.94,64.21+9.87
Uncalibrated,out,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
TS Source,out,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
TS Oracle,out,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
HB,out,82.0+3.66,80.62+0.92,73.45+1.71,70.67+4.71,76.68+5.69
Isotonic,out,78.72+2.71,76.43+1.54,67.83+2.0,66.01+3.77,72.25+6.03
Beta abm,out,77.07+4.3,74.66+2.06,62.71+5.36,58.71+5.15,68.29+8.92
Beta am,out,76.68+4.35,74.43+2.3,62.69+5.4,58.77+5.17,68.14+8.8
Beta ab,out,78.4+4.57,75.8+2.24,63.76+6.07,59.42+6.35,69.34+9.44
TS,out,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
Cluster NN,out,78.0+4.67,75.68+2.31,63.32+6.38,58.8+6.68,68.95+9.68
Cluster LR,out,78.0+4.67,75.69+2.3,63.32+6.38,58.8+6.68,68.95+9.68
Cluster Ensem,out,78.0+4.67,75.69+2.3,63.32+6.38,58.8+6.68,68.95+9.68
CaliGen Er,out,74.57+1.41,73.54+1.12,60.31+3.75,54.15+5.21,65.64+9.31
CaliGen TS Er,out,74.57+1.41,73.54+1.12,60.31+3.75,54.15+5.21,65.64+9.31
CaliGen Ensem Er,out,73.36+2.19,72.25+1.44,58.5+2.54,52.59+6.09,64.18+9.57
CaliGen ECE,out,74.15+0.92,73.89+0.76,60.37+3.81,55.23+5.96,65.91+9.05
CaliGen TS ECE,out,74.15+0.92,73.89+0.76,60.37+3.81,55.23+5.96,65.91+9.05
CaliGen Ensem ECE,out,73.95+1.18,72.35+1.39,58.88+1.94,52.5+5.79,64.42+9.58

### Average the domain wise results for source domains
We also have stored results for std. Here we are abusing the statistics by taking the standard deviation over columns. We ran the 20 iterations over 500 randomly selected samples. By abusing we are treating these columns as single iteration results.

In [31]:
res_mean_in = error_in[MAIN_COLUMNS+['Domain']][(error_in['Train'] == True)].groupby(['Domain']).mean().T
res_std_in = error_in[MAIN_COLUMNS+['Domain']][(error_in['Train'] == True)].groupby(['Domain']).std().T

In [32]:
res_mean_in['Average'] = res_mean_in[['Art', 'Clipart', 'Product', 'RealWorld']].mean(axis=1)

Get the standard deviations for Average. The function is in utils.py

In [33]:
res_std_in['std'] = get_std(res_mean_in, res_std_in)

In [34]:
res_mean_in = res_mean_in.round(2)
res_std_in = res_std_in.round(2)

In [35]:
res_mean_in['Art'] = res_mean_in['Art'].astype(str) + '+' + res_std_in['Art'].astype(str)
res_mean_in['Clipart'] = res_mean_in['Clipart'].astype(str) + '+' + res_std_in['Clipart'].astype(str)
res_mean_in['Product'] = res_mean_in['Product'].astype(str) + '+' + res_std_in['Product'].astype(str)
res_mean_in['RealWorld'] = res_mean_in['RealWorld'].astype(str) + '+' + res_std_in['RealWorld'].astype(str)
res_mean_in['Average'] = res_mean_in['Average'].astype(str) + '+' + res_std_in['std'].astype(str)

In [36]:
res_mean_in['Calibrated on'] = ['in'] * len(res_mean_in)
res_mean_in.rename_axis('Method', axis='columns', inplace=True)

In [37]:
res_mean_in[res_columns]

Method,Calibrated on,Art,Clipart,Product,RealWorld,Average
Uncalibrated,in,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
TS Source,in,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
TS Oracle,in,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
HB,in,8.93+3.61,1.68+0.19,0.26+0.02,9.23+1.48,5.02+4.53
Isotonic,in,49.67+1.79,16.23+0.32,16.47+0.51,27.45+3.89,27.45+13.77
Beta abm,in,0.37+0.01,1.08+0.04,0.12+0.01,0.6+0.06,0.54+0.35
Beta am,in,0.37+0.01,1.07+0.01,0.11+0.01,0.67+0.1,0.56+0.36
Beta ab,in,0.83+0.45,1.06+0.01,0.12+0.0,0.72+0.03,0.68+0.41
TS,in,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
Cluster NN,in,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
Cluster LR,in,0.31+0.0,1.06+0.0,0.12+0.0,1.23+0.29,0.68+0.5
Cluster Ensem,in,0.31+0.0,1.06+0.0,0.12+0.0,1.1+0.16,0.65+0.45
CaliGen Er,in,5.24+1.59,4.73+0.6,0.97+0.11,10.64+2.28,5.4+3.73
CaliGen TS Er,in,5.24+1.59,4.73+0.6,0.97+0.11,10.64+2.28,5.4+3.73
CaliGen Ensem Er,in,0.38+0.01,1.27+0.11,0.13+0.01,2.01+0.36,0.95+0.77
CaliGen ECE,in,5.24+1.59,5.99+0.42,1.11+0.22,11.16+1.94,5.88+3.79
CaliGen TS ECE,in,5.24+1.59,5.99+0.42,1.11+0.22,11.16+1.94,5.88+3.79
CaliGen Ensem ECE,in,0.38+0.01,1.4+0.09,0.14+0.02,2.05+0.32,1.0+0.79

### Average the domain wise results for source domains when source domain not included in calibration domain
We also have stored results for std. Here we are abusing the statistics by taking the standard deviation over columns. We ran the 20 iterations over 500 randomly selected samples. By abusing we are treating these columns as single iteration results.

In [38]:
res_mean_out = error_out[MAIN_COLUMNS+['Domain']][(error_out['Train'] == True)].groupby(['Domain']).mean().T
res_std_out = error_out[MAIN_COLUMNS+['Domain']][(error_out['Train'] == True)].groupby(['Domain']).std().T

Get the standard deviations for Average. The function is in utils.py

In [39]:
res_mean_out['Average'] = res_mean_out[['Art', 'Clipart', 'Product', 'RealWorld']].mean(axis=1)
res_std_out['std'] = get_std(res_mean_out, res_std_out)

In [40]:
res_mean_out = res_mean_out.round(2)
res_std_out = res_std_out.round(2)
res_mean_out['Art'] = res_mean_out['Art'].astype(str) + '+' + res_std_out['Art'].astype(str)
res_mean_out['Clipart'] = res_mean_out['Clipart'].astype(str) + '+' + res_std_out['Clipart'].astype(str)
res_mean_out['Product'] = res_mean_out['Product'].astype(str) + '+' + res_std_out['Product'].astype(str)
res_mean_out['RealWorld'] = res_mean_out['RealWorld'].astype(str) + '+' + res_std_out['RealWorld'].astype(str)
res_mean_out['Average'] = res_mean_out['Average'].astype(str) + '+' + res_std_out['std'].astype(str)

#### Show the results

In [41]:
res_mean_out['Calibrated on'] = ['out'] * len(res_mean_out)
res_mean_out.rename_axis('Method', axis='columns', inplace=True)

In [42]:
res_mean_out[res_columns]

Method,Calibrated on,Art,Clipart,Product,RealWorld,Average
Uncalibrated,out,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
TS Source,out,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
TS Oracle,out,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
HB,out,17.62+7.63,22.52+4.27,23.91+14.04,27.18+11.35,22.81+10.61
Isotonic,out,70.94+6.91,76.23+4.52,76.78+10.95,49.82+10.85,68.44+14.05
Beta abm,out,0.36+0.02,1.08+0.0,0.12+0.01,1.02+0.54,0.65+0.49
Beta am,out,0.36+0.02,1.16+0.07,0.26+0.27,1.39+0.78,0.79+0.64
Beta ab,out,1.77+1.22,5.85+0.55,2.03+2.61,1.31+0.11,2.74+2.33
TS,out,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
Cluster NN,out,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
Cluster LR,out,0.31+0.0,1.06+0.0,0.12+0.0,0.85+0.13,0.58+0.39
Cluster Ensem,out,0.31+0.0,1.06+0.0,0.12+0.0,0.83+0.11,0.58+0.38
CaliGen Er,out,12.52+5.51,25.22+2.95,10.14+4.02,25.02+5.04,18.22+8.27
CaliGen TS Er,out,12.52+5.51,25.22+2.95,10.14+4.02,25.02+5.04,18.22+8.27
CaliGen Ensem Er,out,0.43+0.07,2.03+0.32,0.13+0.01,4.11+1.61,1.68+1.78
CaliGen ECE,out,12.52+5.51,26.72+3.74,12.84+6.72,26.1+7.72,19.54+9.19
CaliGen TS ECE,out,12.52+5.51,26.72+3.74,12.84+6.72,26.1+7.72,19.54+9.19
CaliGen Ensem ECE,out,0.43+0.07,2.1+0.3,0.25+0.11,4.59+2.55,1.84+2.17

## Combined results when source domain included (in) and not included (out) in calibration domains

In [43]:
res = pd.concat([res_mean_in[res_columns], res_mean_out[res_columns]])

In [44]:
res

Method,Calibrated on,Art,Clipart,Product,RealWorld,Average
Uncalibrated,in,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
TS Source,in,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
TS Oracle,in,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
HB,in,8.93+3.61,1.68+0.19,0.26+0.02,9.23+1.48,5.02+4.53
Isotonic,in,49.67+1.79,16.23+0.32,16.47+0.51,27.45+3.89,27.45+13.77
Beta abm,in,0.37+0.01,1.08+0.04,0.12+0.01,0.6+0.06,0.54+0.35
Beta am,in,0.37+0.01,1.07+0.01,0.11+0.01,0.67+0.1,0.56+0.36
Beta ab,in,0.83+0.45,1.06+0.01,0.12+0.0,0.72+0.03,0.68+0.41
TS,in,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
Cluster NN,in,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
Cluster LR,in,0.31+0.0,1.06+0.0,0.12+0.0,1.23+0.29,0.68+0.5
Cluster Ensem,in,0.31+0.0,1.06+0.0,0.12+0.0,1.1+0.16,0.65+0.45
CaliGen Er,in,5.24+1.59,4.73+0.6,0.97+0.11,10.64+2.28,5.4+3.73
CaliGen TS Er,in,5.24+1.59,4.73+0.6,0.97+0.11,10.64+2.28,5.4+3.73
CaliGen Ensem Er,in,0.38+0.01,1.27+0.11,0.13+0.01,2.01+0.36,0.95+0.77
CaliGen ECE,in,5.24+1.59,5.99+0.42,1.11+0.22,11.16+1.94,5.88+3.79
CaliGen TS ECE,in,5.24+1.59,5.99+0.42,1.11+0.22,11.16+1.94,5.88+3.79
CaliGen Ensem ECE,in,0.38+0.01,1.4+0.09,0.14+0.02,2.05+0.32,1.0+0.79
Uncalibrated,out,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
TS Source,out,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
TS Oracle,out,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
HB,out,17.62+7.63,22.52+4.27,23.91+14.04,27.18+11.35,22.81+10.61
Isotonic,out,70.94+6.91,76.23+4.52,76.78+10.95,49.82+10.85,68.44+14.05
Beta abm,out,0.36+0.02,1.08+0.0,0.12+0.01,1.02+0.54,0.65+0.49
Beta am,out,0.36+0.02,1.16+0.07,0.26+0.27,1.39+0.78,0.79+0.64
Beta ab,out,1.77+1.22,5.85+0.55,2.03+2.61,1.31+0.11,2.74+2.33
TS,out,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
Cluster NN,out,0.31+0.0,1.06+0.0,0.12+0.0,0.77+0.0,0.57+0.37
Cluster LR,out,0.31+0.0,1.06+0.0,0.12+0.0,0.85+0.13,0.58+0.39
Cluster Ensem,out,0.31+0.0,1.06+0.0,0.12+0.0,0.83+0.11,0.58+0.38
CaliGen Er,out,12.52+5.51,25.22+2.95,10.14+4.02,25.02+5.04,18.22+8.27
CaliGen TS Er,out,12.52+5.51,25.22+2.95,10.14+4.02,25.02+5.04,18.22+8.27
CaliGen Ensem Er,out,0.43+0.07,2.03+0.32,0.13+0.01,4.11+1.61,1.68+1.78
CaliGen ECE,out,12.52+5.51,26.72+3.74,12.84+6.72,26.1+7.72,19.54+9.19
CaliGen TS ECE,out,12.52+5.51,26.72+3.74,12.84+6.72,26.1+7.72,19.54+9.19
CaliGen Ensem ECE,out,0.43+0.07,2.1+0.3,0.25+0.11,4.59+2.55,1.84+2.17